function [govBudgetGap kOverL] = getTaoFunction(ttao,llambda, kkappa, ggamma, ddelta, ssigmaY,bbeta,aalphaK,depreciation,TFP,...
    nGridShocks,chi,upperBound,a,nAssets,...
    ifLabor,nGridLabor,options)

[kOverL,diff]=fminbnd(@(kOverL) ...
                    generalEqUBIFunction(kOverL,ttao,llambda, kkappa, ggamma, ddelta, ssigmaY,bbeta,aalphaK,depreciation,TFP,...
    nGridShocks,chi,upperBound,a,nAssets,...
    ifLabor,nGridLabor),...
                    0.000001,10,options);
                
[kOverLGap govBudgetGap govBudgetProfit r wage mValue mAssetPolicyIndex mAssetPolicy mConsumptionPolicy mLaborPolicy vStationaryDistribution capitalSupply laborSupplyEffective] = generalEqUBIFunction(kOverL,ttao,llambda, kkappa, ggamma, ddelta, ssigmaY,bbeta,aalphaK,depreciation,TFP,...
    nGridShocks,chi,upperBound,a,nAssets,...
    ifLabor,nGridLabor);

table(kOverLGap,govBudgetGap,govBudgetProfit,r,wage)

% gap = govBudgetGap;

return